//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQuest.Locales {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TQuest.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the correct option.
        /// </summary>
        internal static string choosecorrectvariant {
            get {
                return ResourceManager.GetString("choosecorrectvariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [ The End! ].
        /// </summary>
        internal static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That&apos;s it, you&apos;ve completed such a long, and perhaps dangerous, journey. Thank you for playing this game! But this isn&apos;t all, someday TQuest 2 will be released!.
        /// </summary>
        internal static string gameovertext {
            get {
                return ResourceManager.GetString("gameovertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Inventory: ].
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty.
        /// </summary>
        internal static string inventorynone {
            get {
                return ResourceManager.GetString("inventorynone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need a key!.
        /// </summary>
        internal static string needkey {
            get {
                return ResourceManager.GetString("needkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You found nothing.
        /// </summary>
        internal static string nothingfind {
            get {
                return ResourceManager.GetString("nothingfind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note 1=4.
        /// </summary>
        internal static string notice14 {
            get {
                return ResourceManager.GetString("notice14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note 2=4.
        /// </summary>
        internal static string notice24 {
            get {
                return ResourceManager.GetString("notice24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note 3=4.
        /// </summary>
        internal static string notice34 {
            get {
                return ResourceManager.GetString("notice34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note 4=1.
        /// </summary>
        internal static string notice41 {
            get {
                return ResourceManager.GetString("notice41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note 5=4.
        /// </summary>
        internal static string notice54 {
            get {
                return ResourceManager.GetString("notice54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outdated version installed, update the game on the official website: unkov.su/projects/tquest1.
        /// </summary>
        internal static string oldVersionMessage {
            get {
                return ResourceManager.GetString("oldVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: nightstand with phone.
        /// </summary>
        internal static string room1_action1 {
            get {
                return ResourceManager.GetString("room1_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: doormat.
        /// </summary>
        internal static string room1_action2 {
            get {
                return ResourceManager.GetString("room1_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: front door.
        /// </summary>
        internal static string room1_action3 {
            get {
                return ResourceManager.GetString("room1_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: kitchen.
        /// </summary>
        internal static string room1_action4 {
            get {
                return ResourceManager.GetString("room1_action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: study.
        /// </summary>
        internal static string room1_action5 {
            get {
                return ResourceManager.GetString("room1_action5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: bedroom.
        /// </summary>
        internal static string room1_action6 {
            get {
                return ResourceManager.GetString("room1_action6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: attic.
        /// </summary>
        internal static string room1_action7 {
            get {
                return ResourceManager.GetString("room1_action7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in the hallway. Behind you is the door to the street, on the left is the kitchen, on the right is the bedroom, in front of you is the door to the study and the stairs. There&apos;s a nightstand with a phone against the wall, and a dirty doormat on the floor..
        /// </summary>
        internal static string room1_description {
            get {
                return ResourceManager.GetString("room1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Doormat] You found a note 1=4.
        /// </summary>
        internal static string room1_notice14_find {
            get {
                return ResourceManager.GetString("room1_notice14_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Doormat] You have already examined this place.
        /// </summary>
        internal static string room1_notice14_finded {
            get {
                return ResourceManager.GetString("room1_notice14_finded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: fork.
        /// </summary>
        internal static string room10_action1 {
            get {
                return ResourceManager.GetString("room10_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: grotto.
        /// </summary>
        internal static string room10_action2 {
            get {
                return ResourceManager.GetString("room10_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The descent down is quite steep, but protruding tree roots help you not to fall. Ahead it&apos;s noticeably lighter and you can make out a spacious grotto, the fork is left behind..
        /// </summary>
        internal static string room10_description {
            get {
                return ResourceManager.GetString("room10_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: backpack.
        /// </summary>
        internal static string room11_action1 {
            get {
                return ResourceManager.GetString("room11_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: junk.
        /// </summary>
        internal static string room11_action2 {
            get {
                return ResourceManager.GetString("room11_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: descent down.
        /// </summary>
        internal static string room11_action3 {
            get {
                return ResourceManager.GetString("room11_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A fire burns in the middle of the grotto. Near it, on a large stone, lies a backpack and a thermos. The coffee in the thermos is still warm. In the far corner, there&apos;s a pile of various garbage and junk..
        /// </summary>
        internal static string room11_description {
            get {
                return ResourceManager.GetString("room11_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: box.
        /// </summary>
        internal static string room12_action1 {
            get {
                return ResourceManager.GetString("room12_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: old skull.
        /// </summary>
        internal static string room12_action2 {
            get {
                return ResourceManager.GetString("room12_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: fork.
        /// </summary>
        internal static string room12_action3 {
            get {
                return ResourceManager.GetString("room12_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In the darkness, you felt a wall and some kind of recess in it. In this niche, there turned out to be a box. In the corner, you hear wheezing sounds. With your foot, you accidentally kicked a dim skull..
        /// </summary>
        internal static string room12_description {
            get {
                return ResourceManager.GetString("room12_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Box] You found a note 5=4.
        /// </summary>
        internal static string room12_notice54_find {
            get {
                return ResourceManager.GetString("room12_notice54_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Box] You have already examined this place.
        /// </summary>
        internal static string room12_notice54_finded {
            get {
                return ResourceManager.GetString("room12_notice54_finded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: table.
        /// </summary>
        internal static string room2_action1 {
            get {
                return ResourceManager.GetString("room2_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: kitchen cabinet.
        /// </summary>
        internal static string room2_action2 {
            get {
                return ResourceManager.GetString("room2_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: sink.
        /// </summary>
        internal static string room2_action3 {
            get {
                return ResourceManager.GetString("room2_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: hallway.
        /// </summary>
        internal static string room2_action4 {
            get {
                return ResourceManager.GetString("room2_action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: basement.
        /// </summary>
        internal static string room2_action5 {
            get {
                return ResourceManager.GetString("room2_action5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in the kitchen. There&apos;s simple kitchen furnishings here: a table with chairs, a sink, and a kitchen cabinet with various plates, glasses, and jars of cereal. There&apos;s a hatch on the floor..
        /// </summary>
        internal static string room2_description {
            get {
                return ResourceManager.GetString("room2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Kitchen cabinet] You found a note 2=4.
        /// </summary>
        internal static string room2_notice24_find {
            get {
                return ResourceManager.GetString("room2_notice24_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Kitchen cabinet] You have already examined this place.
        /// </summary>
        internal static string room2_notice24_finded {
            get {
                return ResourceManager.GetString("room2_notice24_finded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The safe password turned out to be correct, well done! Here&apos;s your key.
        /// </summary>
        internal static string room3_acceptpassword {
            get {
                return ResourceManager.GetString("room3_acceptpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: bookshelf.
        /// </summary>
        internal static string room3_action1 {
            get {
                return ResourceManager.GetString("room3_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: desk.
        /// </summary>
        internal static string room3_action2 {
            get {
                return ResourceManager.GetString("room3_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: safe.
        /// </summary>
        internal static string room3_action3 {
            get {
                return ResourceManager.GetString("room3_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: hallway.
        /// </summary>
        internal static string room3_action4 {
            get {
                return ResourceManager.GetString("room3_action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in the study. By the window there&apos;s a desk with an armchair, in the corner of the study stands a massive safe with a combination lock. Along the wall there&apos;s a bookshelf filled with many books..
        /// </summary>
        internal static string room3_description {
            get {
                return ResourceManager.GetString("room3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Bookshelf] You found a note 4=1.
        /// </summary>
        internal static string room3_notice41_find {
            get {
                return ResourceManager.GetString("room3_notice41_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Bookshelf] You have already examined this place.
        /// </summary>
        internal static string room3_notice41_finded {
            get {
                return ResourceManager.GetString("room3_notice41_finded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Safe] Enter the safe password using the notes you&apos;ve found. Hint: there should be 5 notes.
        /// </summary>
        internal static string room3_password {
            get {
                return ResourceManager.GetString("room3_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong password, think again.
        /// </summary>
        internal static string room3_wrongpassword {
            get {
                return ResourceManager.GetString("room3_wrongpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: bed.
        /// </summary>
        internal static string room4_action1 {
            get {
                return ResourceManager.GetString("room4_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: floor lamp.
        /// </summary>
        internal static string room4_action2 {
            get {
                return ResourceManager.GetString("room4_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: wardrobe.
        /// </summary>
        internal static string room4_action3 {
            get {
                return ResourceManager.GetString("room4_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: hallway.
        /// </summary>
        internal static string room4_action4 {
            get {
                return ResourceManager.GetString("room4_action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in the bedroom. In the middle of the room stands a bed, against the wall there&apos;s a wardrobe. You also see a beautiful floor lamp near the bed, filling the room with soft light..
        /// </summary>
        internal static string room4_description {
            get {
                return ResourceManager.GetString("room4_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: old bicycle.
        /// </summary>
        internal static string room5_action1 {
            get {
                return ResourceManager.GetString("room5_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: boxes.
        /// </summary>
        internal static string room5_action2 {
            get {
                return ResourceManager.GetString("room5_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: worn-out felt boots.
        /// </summary>
        internal static string room5_action3 {
            get {
                return ResourceManager.GetString("room5_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: hallway.
        /// </summary>
        internal static string room5_action4 {
            get {
                return ResourceManager.GetString("room5_action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: roof.
        /// </summary>
        internal static string room5_action5 {
            get {
                return ResourceManager.GetString("room5_action5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in the attic. The skylight window is broken. Boxes are lying in the corner, an old bicycle is hanging from the ceiling, and worn-out felt boots are on the floor..
        /// </summary>
        internal static string room5_description {
            get {
                return ResourceManager.GetString("room5_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Worn-out felt boots] You found a note 3=4.
        /// </summary>
        internal static string room5_notice34_find {
            get {
                return ResourceManager.GetString("room5_notice34_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Worn-out felt boots] You have already examined this place.
        /// </summary>
        internal static string room5_notice34_finded {
            get {
                return ResourceManager.GetString("room5_notice34_finded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: chimney.
        /// </summary>
        internal static string room6_action1 {
            get {
                return ResourceManager.GetString("room6_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: nest.
        /// </summary>
        internal static string room6_action2 {
            get {
                return ResourceManager.GetString("room6_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: attic.
        /// </summary>
        internal static string room6_action3 {
            get {
                return ResourceManager.GetString("room6_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are on the roof. Be careful, don&apos;t fall! In the center rises a brick chimney. And at the very edge, some birds have built a nest..
        /// </summary>
        internal static string room6_description {
            get {
                return ResourceManager.GetString("room6_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: washing machine.
        /// </summary>
        internal static string room7_action1 {
            get {
                return ResourceManager.GetString("room7_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на examine: pile of clothes.
        /// </summary>
        internal static string room7_action2 {
            get {
                return ResourceManager.GetString("room7_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: kitchen.
        /// </summary>
        internal static string room7_action3 {
            get {
                return ResourceManager.GetString("room7_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: breach.
        /// </summary>
        internal static string room7_action4 {
            get {
                return ResourceManager.GetString("room7_action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in the basement. It&apos;s quite damp and dark here, but you can make out a rusty washing machine, a pile of rags in a basket, and also some kind of breach in the wall..
        /// </summary>
        internal static string room7_description {
            get {
                return ResourceManager.GetString("room7_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: basement.
        /// </summary>
        internal static string room8_action1 {
            get {
                return ResourceManager.GetString("room8_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: fork.
        /// </summary>
        internal static string room8_action2 {
            get {
                return ResourceManager.GetString("room8_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The basement is behind you. You are in the breach. It&apos;s very cramped here and almost nothing is visible. But ahead, the passage widens enough and you can see a fork..
        /// </summary>
        internal static string room8_description {
            get {
                return ResourceManager.GetString("room8_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: breach.
        /// </summary>
        internal static string room9_action1 {
            get {
                return ResourceManager.GetString("room9_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: descent down.
        /// </summary>
        internal static string room9_action2 {
            get {
                return ResourceManager.GetString("room9_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на go: cave.
        /// </summary>
        internal static string room9_action3 {
            get {
                return ResourceManager.GetString("room9_action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The cave has expanded sharply. It&apos;s much more spacious here. There&apos;s a fork in front of you, rustling sounds are coming from the right cave. The left one goes sharply downward and light is visible from below..
        /// </summary>
        internal static string room9_description {
            get {
                return ResourceManager.GetString("room9_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have already examined this place.
        /// </summary>
        internal static string searchthis {
            get {
                return ResourceManager.GetString("searchthis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the required action.
        /// </summary>
        internal static string typeneedaction {
            get {
                return ResourceManager.GetString("typeneedaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Options: ].
        /// </summary>
        internal static string variants {
            get {
                return ResourceManager.GetString("variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to TQuest 1!
        ///.
        /// </summary>
        internal static string welcomemessage {
            get {
                return ResourceManager.GetString("welcomemessage", resourceCulture);
            }
        }
    }
}
